
spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev
  application:
    name: schedule
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://113.125.103.168:3306/scheduling?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      url: jdbc:mysql://113.125.103.168:3306/scheduling?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true
      #      url: jdbc:mysql://localhost:3306/scheduling?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true
      username: scheduling
      password: 12qw!@QW
---
server:
  port: 8085
spring:
  profiles: pro
  application:
    name: schedule
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://113.125.103.168:3306/scheduling?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      url: jdbc:mysql://113.125.103.168:3306/scheduling?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true
      url: jdbc:mysql://localhost:3306/scheduling?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true
      username: scheduling
      password: 12qw!@QW
---


mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      insert-strategy: ignored
