server:
  port: 8081
spring:
  application:
    name: schedule
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://113.125.103.168:3306/scheduling?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      url: jdbc:mysql://113.125.103.168:3306/scheduling
      username: scheduling
      password: 12qw!@QW
mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
