
spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev
  application:
    name: schedule
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://113.125.103.168:3306/scheduling?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      url: jdbc:mysql://113.125.103.168:3306/scheduling?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true
      #      url: jdbc:mysql://localhost:3306/scheduling?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true
      username: scheduling
      password: 12qw!@QW
---
server:
  port: 8085
spring:
  profiles: pro
  application:
    name: schedule
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://113.125.103.168:3306/scheduling?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      url: jdbc:mysql://113.125.103.168:3306/scheduling?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true
      url: jdbc:mysql://localhost:3306/scheduling?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true
      username: scheduling
      password: 12qw!@QW
---


mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      insert-strategy: ignored
spring:
  mail:
    host: smtp.163.com
    username: chenyikeji0000@163.com
    password: VJOFLTKZBKIPOUHX
  redis:
    host: 113.125.103.168
    port: 6379
    database: 0
    password: qweewqQWEEWQ
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0